<a href="https://colab.research.google.com/github/Talhaa07/python_ka_chila/blob/main/Numpy_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
## One Dimensional Array

np = np.array([1,2,3,4,5,6,7,8,9,10])
np

##it also be called vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
## Two Dimensional array         ## can be called as matrix
b=np.array([[1,2,3],[4,5,6]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
## 3 Dimensional array                           ##called as tensor
c=np.array([[[1,2,3,4],[5,6,7,8],[9,0,3,4]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 0, 3, 4]]])

In [ ]:
 f=np.array([1,2,3,4,5,6,7,8],dtype=float)
 f

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
## arrange numpy

np.arange(1,23)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [ ]:
## Reshape array

p=np.arange(1,11).reshape(2,5)
p

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.ones((3,4))    ## one array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,5))         ##zeros array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.random.random((3,5))        ##random arrays

array([[0.39571674, 0.1233154 , 0.36480449, 0.58146923, 0.72306403],
       [0.68084399, 0.42575582, 0.05642305, 0.7237764 , 0.08413271],
       [0.10517158, 0.68384065, 0.01259644, 0.34993443, 0.26320491]])

In [ ]:
## np.linear space calaculte distance between two spaces in equal parts

np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
np.identity(2)           ##identity one in diagonal 

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a1=np.arange(1,10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(14).reshape(2,7)

In [ ]:
a1.ndim       ## to check dimension of arrays

1

In [ ]:
a3.shape 
         ## to check shape

(2, 7)


In [ ]:
a2.itemsize

8

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a3.astype(np.int32)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]], dtype=int32)

In [8]:
 a1=np.arange(12).reshape(3,4)
 a2=np.arange(12,24).reshape(3,4)

In [10]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [11]:
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [12]:
a2<20

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [13]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [14]:
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [15]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

Array_Functions every mathematical steps hav ecertain function


In [30]:
a1=np.random.random(12)

In [31]:
a1=np.round(a1*100)

In [32]:
a1

array([ 44.,  19.,  58.,   1.,  61., 100.,  92.,  97.,  96.,  68.,  26.,
        33.])

In [19]:
np.max(a1)

99.0

In [20]:
np.min(a1)

4.0

In [21]:
np.sum(a1)

620.0

In [22]:
np.product(a1)

6.121722097463132e+18

In [23]:
## 0 ==>  col and 1 ==> row

np.max(a1,axis=0)

99.0

In [25]:
np.max(a1,axis=1)

AxisError: ignored

In [26]:
np.sum(a1,axis=0)

620.0

In [34]:
np.product(a1)

1.4783970974375117e+19

In [35]:
## similarly we


np.mean(a1)

57.916666666666664

In [36]:
###  np.std(a1,axis=0), np.mean(a1,axis=0),np.var(a1,axis=1)

np.sin(a1)

array([ 0.01770193,  0.14987721,  0.99287265,  0.84147098, -0.96611777,
       -0.50636564, -0.77946607,  0.37960774,  0.98358775, -0.89792768,
        0.76255845,  0.99991186])

In [37]:
#dot product

a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)

In [38]:
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [39]:
np.log(a1)

<ipython-input-39-f50b4f369011>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [40]:
np.exp(a2)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [44]:
a1=np.random.random((2,3))*100


In [45]:
np.round(a1)

array([[ 0., 64., 14.],
       [42., 69., 78.]])

In [46]:
np.floor(a1)

array([[ 0., 64., 14.],
       [41., 69., 77.]])

In [47]:
np.ceil(a1)

array([[ 1., 65., 15.],
       [42., 70., 78.]])

In [50]:
a1=np.arange(13)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [51]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
a1[4]

4

In [53]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
## 0=> 1st row, 1==> 2nd row, 3==> 3rd row
a2[1,2]

6

In [56]:
a2[2,3]

11

In [57]:
a2[1,2]

6

In [58]:
a2[1,1]

5

In [59]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [60]:
a3[0,1,0]

2

In [61]:
a3[1,1,1]

7

In [62]:
a3[0,0,0]

0

In [63]:
a1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
a1[2:6]

array([2, 3, 4, 5])

In [65]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
a2[0,:]

array([0, 1, 2, 3])

In [69]:
a2[:,1]

array([1, 5, 9])

In [70]:
a2[:,2]

array([ 2,  6, 10])

In [71]:
a2[:,3]

array([ 3,  7, 11])

In [72]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [74]:
a2[0:3,0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [77]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [79]:
a2[1::,1::3]

array([[5],
       [9]])

In [80]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a2[0::1,1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [85]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [87]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [88]:
a3[0:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [89]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [91]:
a3[0,0:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [94]:
a3[0,1,:]

array([3, 4, 5])

In [95]:
a3[1,:,1]

array([10, 13, 16])

In [96]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [98]:
a3[0::1]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
a3


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [100]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [101]:
##loops
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12


In [102]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [104]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [106]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [107]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [108]:
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [109]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [110]:
## skacking horizentally and vertically

a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [111]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [113]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [114]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [115]:
## splitting opposite of stacking can horizenally and vertically

np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [116]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]